### ISSUE TITLE
execute_iter 

### ISSUE THREAD

**Issue by danlittlejohn** [mymarilyn/clickhouse-driver#103]
Trying to use execute_iter() and getting a error with the iterator object.  Works fine for execute(). Using version 0.20.

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/wsgiref/handlers.py", line 179, in finish_response
    for data in self.result:
  File "/app/apps/analytics_app/views.py", line 518, in csv_row_generator
    for rows in row_iterator:
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/client.py", line 86, in iter_receive_result
    for rows in IterQueryResult(gen, with_column_types=with_column_types):
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/result.py", line 115, in next
    packet = next(self.packet_generator)
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/client.py", line 93, in packet_generator
    packet = self.receive_packet()
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/client.py", line 107, in receive_packet
    packet = self.connection.receive_packet()
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 388, in receive_packet
    packet.type = packet_type = read_varint(self.fin)
  File "/opt/app-root/lib/python3.6/site-packages/clickhouse_driver/reader.py", line 30, in read_varint
    i = f.read_one()
AttributeError: 'NoneType' object has no attribute 'read_one'

**Comment by xzkostyan** [comment]
Hi. Can you provide minimal snippet to reproduce this problem?

**Comment by danlittlejohn** [comment]
Sure, here it is

        client = Clickhouse.create_client()
        row_iterator = client.execute_iter(
            f"""
            SELECT *
            FROM table
            LIMIT 5000
            """,
            settings={'max_block_size': 100000},
        )
        client.disconnect()

        for row in row_iterator:
            print(row)

I upgraded to 0.1.0 and it has the same problem.

**Comment by xzkostyan** [comment]
Just do not call `disconnect` after `execute_iter`. 

```python
    client = Clickhouse.create_client()
    row_iterator = client.execute_iter(
        f"""
        SELECT *
        FROM table
        LIMIT 5000
        """,
        settings={'max_block_size': 100000},
    )

    for row in row_iterator:
        print(row)
   # call client.disconnect() here if you want explicit socket disposal
```

**Comment by danlittlejohn** [comment]
oops.  That was it.  Thanks very much.
