### ISSUE TITLE
insert error with aioch

### ISSUE THREAD

**Issue by llj098** [mymarilyn/clickhouse-driver#119]
hi, 

below is my code, insert with pandas data frame:

```
...
        bts['symbol'] = 'btc_usdt'                                                                                                                                                                                 
        sql = 'INSERT INTO metrics.trade_bucket(vol, flow, timestamp, exchange, symbol, flow_ratio, cdf) VALUES';                                                                                                  
        await ch_client.execute(sql, bts.to_dict(orient='records'))           
...
```

it sucess for first a few times, but later it will show:

```
[ERROR]2019-11-12 16:12:51,180-[base_events.py:L1285] Task exception was never retrieved
future: <Task finished coro=<save_db() done, defined at main.py:121> exception=UnexpectedPacketFromServerError('Unexpected packet from server localhost:9000 (expected Pong, got EndOfStream)',)>
Traceback (most recent call last):
  File "main.py", line 129, in save_db
    await ch_client.execute(sql, bts.to_dict(orient='records'))
  File "/usr/local/lib/python3.6/dist-packages/aioch/client.py", line 92, in execute
    **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 196, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/connection.py", line 174, in force_connect
    elif not self.ping():
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/connection.py", line 365, in ping
    raise errors.UnexpectedPacketFromServerError(msg)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server localhost:9000 (expected Pong, got EndOfStream)
[ERROR]2019-11-12 16:12:51,181-[base_events.py:L1285] Task exception was never retrieved
future: <Task finished coro=<save_db() done, defined at main.py:121> exception=ServerException('DB::NetException. DB::NetException: Unexpected packet Data received from client. Stack trace:\n\n0. 0x55b9d08ae640 
StackTrace::StackTrace() /usr/bin/clickhouse\n1. 0x55b9d08ae415 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse\n2. 0x55b
9d046f533 ? /usr/bin/clickhouse\n3. 0x55b9d098b309 DB::TCPHandler::receivePacket() /usr/bin/clickhouse\n4. 0x55b9d098c8a4 DB::TCPHandler::runImpl() /usr/bin/clickhouse\n5. 0x55b9d098d4fb DB::TCPHandler::run() /u
sr/bin/clickhouse\n6. 0x55b9d47c13c0 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse\n7. 0x55b9d47c1add Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse\n8. 0x55b9d5e4b901 Poco::PooledThread
::run() /usr/bin/clickhouse\n9. 0x55b9d5e496ac Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse\n10. 0x55b9d65beeb0 ? /usr/bin/clickhouse\n11. 0x7fc1597a56db start_thread /lib/x86_64-linux-gnu/libpthre
ad-2.27.so\n12. 0x7fc1590c288f __clone /lib/x86_64-linux-gnu/libc-2.27.so\n', 101)>
Traceback (most recent call last):
  File "main.py", line 129, in save_db
    await ch_client.execute(sql, bts.to_dict(orient='records'))
  File "/usr/local/lib/python3.6/dist-packages/aioch/client.py", line 92, in execute
    **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 207, in execute
    query_id=query_id, types_check=types_check
  File "/usr/local/lib/python3.6/dist-packages/clickhouse_driver/client.py", line 364, in process_insert_query
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 101.
DB::NetException. DB::NetException: Unexpected packet Data received from client. Stack trace:

0. 0x55b9d08ae640 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x55b9d08ae415 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x55b9d046f533 ? /usr/bin/clickhouse
3. 0x55b9d098b309 DB::TCPHandler::receivePacket() /usr/bin/clickhouse
4. 0x55b9d098c8a4 DB::TCPHandler::runImpl() /usr/bin/clickhouse
5. 0x55b9d098d4fb DB::TCPHandler::run() /usr/bin/clickhouse
6. 0x55b9d47c13c0 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
7. 0x55b9d47c1add Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
8. 0x55b9d5e4b901 Poco::PooledThread::run() /usr/bin/clickhouse
9. 0x55b9d5e496ac Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
10. 0x55b9d65beeb0 ? /usr/bin/clickhouse
11. 0x7fc1597a56db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
12. 0x7fc1590c288f __clone /lib/x86_64-linux-gnu/libc-2.27.so

^[[5~^[[5~^[^[[5~^CTraceback (most recent call last):
  File "main.py", line 284, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)

```

I'm using aioch, since it's a wrapper, I post the issue here. Not always error, sometime works OK, sometimes show the exceptions above. 

Versions:

- clickhouse-driver: 0.12.0
- aioch: 0.0.1
- clickhouse server: 19.15
- python 3.6.9
- os: ubuntu 16.04

**Comment by xzkostyan** [comment]
Hi.

Do you share `ch_client` instance between multiple asyncio tasks?

**Comment by llj098** [comment]
Yes I share the same client object

Konstantin Lebedev <notifications@github.com> 于 2019年11月23日周六 02:37写道：

**Comment by xzkostyan** [comment]
Well, you should not do it. A little background why this won't work is available here: https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html#async-and-multithreading
