### ISSUE TITLE
ImportError: .../varint.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by edwinkong** [mymarilyn/clickhouse-driver#131]
- **Problem**
When executing `import clickhouse_driver` in a virtualenv, an ImportError was raised.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/__init__.py", line 2, in <module>
    from .client import Client
  File "/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 6, in <module>
    from .block import ColumnOrientedBlock, RowOrientedBlock
  File "/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/block.py", line 1, in <module>
    from .reader import read_varint, read_binary_uint8, read_binary_int32
  File "/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/reader.py", line 3, in <module>
    from .varint import read_varint
ImportError: /home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/varint.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted
```
Running the Python as root, no avail.

- **Environment**
Python version: Python 3.6.8 
OS version: RedHat Enterprise Linux 7.5
Driver version: clickhouse _driver==0.1.3
ClickHouse version: ClickHouse client version 19.16.2.2 (official build).

- **Strace Result**
open("/home/pipeline/counter_pipeline/venv/lib/python3.6/site-packages/_virtualenv.pth", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0754, st_size=18, ...}) = 0
ioctl(3, TCGETS, 0x7ffd9e941c10)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
ioctl(3, TCGETS, 0x7ffd9e941ba0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "import _virtualenv", 8192)     = 18
read(3, "", 8192)                       = 0
read(3, "", 8192)                       = 0
close(3)                                = 0
open("/home/pipeline/counter_pipeline/venv/lib/python3.6/site-packages/pytest-cov.pth", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=376, ...}) = 0
ioctl(3, TCGETS, 0x7ffd9e941c10)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
ioctl(3, TCGETS, 0x7ffd9e941ba0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "import os, sys;exec('if \\'COV_CO"..., 8192) = 376
read(3, "", 8192)                       = 0
read(3, "", 8192)                       = 0
close(3)                                = 0
stat("/usr/lib64/python3.6", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
stat("/usr/lib64/python3.6/lib-dynload", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages", {st_mode=S_IFDIR|0775, st_size=289, ...}) = 0
stat("/home/pipeline/counter_pipeline/venv/lib/python3.6/site-packages", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
write(2, "  File \"<string>\", line 1\n", 26  File "<string>", line 1
) = 26
write(2, "    from clickhouse-driver impor"..., 41    from clickhouse-driver import Client
) = 41
write(2, "                   ^\n", 21                   ^
)  = 21
write(2, "SyntaxError: invalid syntax\n", 28SyntaxError: invalid syntax
) = 28
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f3cc75e8630}, {sa_handler=0x7f3cc79e5870, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f3cc75e8630}, 8) = 0
munmap(0x7f3cc02d3000, 262144)          = 0
sigaltstack(NULL, {ss_sp=0x8bb990, ss_flags=0, ss_size=8192}) = 0
sigaltstack({ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}, NULL) = 0
exit_group(1)                           = ?
+++ exited with 1 +++

- **Permission Settings**
```
$ ls -alF
...
-rwxr-xr--  1 pipeline pipeline     18 Mar 13 11:28 _virtualenv.pth*
-r-xr-xr-x  1 pipeline pipeline   4443 Mar 13 11:28 _virtualenv.py*
```

- **Additional Information**
It worked in another miniconda3 environment.

**Comment by xzkostyan** [comment]
From stace log:

```
open("/home/pipeline/counter_pipeline/venv/lib64/python3.6/site-packages/clickhouse_driver/varint.cpython-36m-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220 \0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0775, st_size=148712, ...}) = 0
mmap(NULL, 2127816, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = -1 EPERM (Operation not permitted)
close(3)
```
Is this a permission issue?
