### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by pete312** [mymarilyn/clickhouse-driver#136]
There are 6 levels of stack trace in the clickhouse_driver module between the database exception and the client code which had a database syntax error.  

It would aid readability to report the stack trace from the point at which the client code called the execute as the syntax error is clearly not anything to do with the clickhouse_driver code stack.

for example 
```
Traceback (most recent call last):
  File "./rebuildtable.py", line 77, in <module>
    print(heuristics(conn, table, 'alpha'))
  File "./rebuildtable.py", line 64, in heuristics
    return conn.execute("blah blah")
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/client.py", line 218, in execute
    columnar=columnar
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/client.py", line 341, in process_ordinary_query
    columnar=columnar)
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/client.py", line 83, in receive_result
    return result.get_result()
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/result.py", line 48, in get_result
    for packet in self.packet_generator:
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/client.py", line 95, in packet_generator
    packet = self.receive_packet()
  File "/home/simplex/.one/lib/python3.6/site-packages/clickhouse_driver/client.py", line 112, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 1: blah blah. 

```

could be reduced to 

```
Traceback (most recent call last):
  File "./rebuildtable.py", line 77, in <module>
    print(heuristics(conn, table, 'alpha'))
  File "./rebuildtable.py", line 64, in heuristics
    return conn.execute("blah blah")

clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 1: blah blah.
```

**Comment by Slach** [comment]
IMHO skip stacktrace frames, could make debug impossible
don't be scary about 6 level frames ;)
just look at java/.net ;) where 20-50 levels and feel your luck ;)

**Comment by pete312** [comment]
When an api is stable it should be clear that the client syntax holds the vast majority of issues. The api can capture and regrow that syntax error at the point of entry cleaning up the stack. The small percentage of api induced problems are usually solved by logging instead of adding many levels to the stack.
