### ISSUE TITLE
All fields mandatory during insert?

### ISSUE THREAD

**Issue by kulkarnikv** [mymarilyn/clickhouse-driver#138]
While executing insert statement, the driver is throwing KeyError. Is this a known behavior or a bug or I am not using some setting? 

clickhouse-driver version - 0.1.3
clickhouse server version - 20.4.4

**Using native client:**

`clickhouse.us-central1-dev.internal :) insert into r format JSONEachRow {"a":"a1"}`
INSERT INTO r FORMAT JSONEachRow
Ok.
1 rows in set. Elapsed: 0.030 sec. 

**Using clickhouse-driver on python:**

`>>> from clickhouse_driver import Client`
`>>> clickhouse_client = Client('XXX.XXX.XXX.XXX')`
`>>> clickhouse_client.execute('describe r')`
[('a', 'String', '', '', '', '', ''), ('b', 'String', '', '', '', '', '')]
`>>> clickhouse_client.execute('insert into r format JSONEachRow', [{"a":"a1", "b":"b1"}])`
1
`>>> clickhouse_client.execute('insert into r format JSONEachRow', [{"a":"a1"}])`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/client.py", line 211, in execute
    columnar=columnar
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/client.py", line 366, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/client.py", line 400, in send_data
    types_check=types_check)
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/block.py", line 39, in __init__
    self.data = self.normalize(data or [])
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/block.py", line 127, in normalize
    self._mutate_dicts_to_rows(data)
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/block.py", line 161, in _mutate_dicts_to_rows
    data[i] = [row[name] for name in column_names]
  File "/Users/koushikkulkarni/opt/anaconda3/lib/python3.7/site-packages/clickhouse_driver/block.py", line 161, in <listcomp>
    data[i] = [row[name] for name in column_names]
KeyError: 'b'

**Comment by xzkostyan** [comment]
Hi.

`FORMAT` clause is not supported. If you omit columns clause before `VALUES` in `INSERT` you should pass all the columns.

So, you have 2 possible ways of data inserting:
1) `INSERT INTO test VALUES`
2) `INSERT INTO test (a, b, c) VALUES`

**Comment by kulkarnikv** [comment]
Alright, thanks for the explanation!
