### ISSUE TITLE
UnexpectedPacketFromServerError while trying to use clickhouse-driver

### ISSUE THREAD

**Issue by atercygnus** [mymarilyn/clickhouse-driver#145]
I have clickhouse on production and try to make queryes using clickhouse-driver.

Minimal code snippet:
```
#! /usr/local/bin/python3.6

from clickhouse_driver import Client

client = Client(
    host='myserver.com',
    database='default',
    port=9090,
    user='user',
    password='password'
)

print(client.execute('select 1'))
```

gives an error:

```
Traceback (most recent call last):
  File "./ch_test_2.py", line 13, in <module>
    print(client.execute('select 1'))
  File "/home/beglyak/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 205, in execute
    self.connection.force_connect()
  File "/home/beglyak/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 180, in force_connect
    self.connect()
  File "/home/beglyak/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 256, in connect
    return self._init_connection(host, port)
  File "/home/beglyak/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 238, in _init_connection
    self.receive_hello()
  File "/home/beglyak/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 374, in receive_hello
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server None:None (expected Hello or Exception, got Unknown packet)
```

Same credentials using http works fine.

**Comment by xzkostyan** [comment]
Affected package version? Server version?

**Comment by atercygnus** [comment]
clickhouse-driver         0.1.4

I cannot define server version. Googled, it can be done using clickhouse-client, but I don't have one. Trying to install it isn't sucessfull.
```
$ sudo apt-get install -y clickhouse-client
[sudo] password for beglyak:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package clickhouse-client
```

**Comment by xzkostyan** [comment]
`select version()` in `clickhouse-client ` will show server version.

**Comment by atercygnus** [comment]
Clickhouse server version: 19.17.4.11

**Comment by xzkostyan** [comment]
Cannot reproduce issue:

```bash
$ docker run -d -p 59000:9000  yandex/clickhouse-server:19.17.4.11 ; sleep 10s ; python -c "from clickhouse_driver import Client; print(Client.from_url('clickhouse://localhost:59000/default').execute('select version()'))"
a1ea11fff2147d22283ad8dd5c89752bab4eaf7b1a9b62e3151197a0ebf04edb
[('19.17.4.11',)]
```

Check server port.

**Comment by atercygnus** [comment]
Probably, we can use only http connection to clickhouse-server in our network, figuring it out with our system administrators.

If so, the problem is clickhouse-driver can only use TCP connection.

**Comment by xzkostyan** [comment]
Working only over native protocol is feature of this package.

**Comment by atercygnus** [comment]
Yes, the problem is due to Chproxy.

[`Chproxy may accept requests over HTTP and HTTPS protocols.`](https://github.com/Vertamedia/chproxy#server)
