### ISSUE TITLE
TypeError: cannot unpack non-iterable int object after running `cursor.execute`

### ISSUE THREAD

**Issue by vladignatyev** [mymarilyn/clickhouse-driver#148]
**Describe the bug**
What I'm trying to do is to load `.csv` file into Clickhouse using the code below:
```python
class warehouse:
    @classmethod
    def load_data_file(cls, filename):
        from csv import DictReader
        from datetime import datetime

        def iter_csv(filename):
            converters = {
                'date_ref': lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'),
                'clicks': lambda x: float(x),
                'impressions': lambda x: float(x),
                'position': lambda x: float(x),
                'ctr': lambda x: float(x)
            }
            with open(filename, 'r') as f:
                reader = DictReader(f, fieldnames=('site_url', 'page', 'keyword', 'date_ref', 'clicks', 'impressions', 'position', 'ctr'))
                for line in reader:
                    row_as_dict = {k: (converters[k](v) if k in converters else v) for k, v in line.items()}
                    yield row_as_dict

        with cls.cursor() as cursor:
           cursor.execute(insert_batch_sql, iter_csv(filename))
```

**To Reproduce**
1. Create csv with values for fields `'site_url', 'page', 'keyword', 'date_ref', 'clicks', 'impressions', 'position', 'ctr'` and load this csv using the code snippet above.
2. Get Exception in Clickhouse driver.
3. Code for getting the `cursor` variable:  `conn = connect(settings.SEARCH_CONSOLE_WAREHOUSE_URL); conn.cursor()`

**Expected behavior**
No exceptions and data loaded as well.

**Versions**

- clickhouse-driver==0.1.3
- Python 3.8

See the exception below.

```
======================================================================
ERROR: test_initial (tests.reports.WarehouseReportsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ignatev/demo/project/tests/base.py", line 35, in setUp
    super(BaseViewTestCase, self).setUp()
  File "/Users/ignatev/demo/project/tests/base.py", line 20, in setUp
    warehouse.connection.load_data_file(self.fixture)
  File "/Users/ignatev/demo/project/warehouse.py", line 60, in load_data_file
    cursor.execute(insert_batch_sql, iter_csv(filename))
  File "/Users/ignatev/env/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 108, in execute
    self._process_response(response)
  File "/Users/ignatev/env/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 293, in _process_response
    rows, columns_with_types = response
TypeError: cannot unpack non-iterable int object
```

**Comment by xzkostyan** [comment]
For data inserting [executemany](https://www.python.org/dev/peps/pep-0249/#executemany) should be used.

> The parameters may also be specified as list of tuples to e.g. insert multiple rows in a single operation, but this kind of usage is deprecated: .executemany() should be used instead.
