### ISSUE TITLE
clickhouse_driver.errors.SocketTimeoutError: Code: 209. 

### ISSUE THREAD

**Issue by sunyongsheng112** [mymarilyn/clickhouse-driver#153]
Python 3.7.1 (default, Jun 28 2020, 14:14:13) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from clickhouse_driver.client import Client
>>> client = Client('localhost',port= 8123, password='UHXQQmhb' )
>>> client.execute("SELECT timestamp from ft_match_predication_all where  timestamp like '2020-07-05 %' limit 1")
Failed to connect to localhost:8123
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 256, in connect
    return self._init_connection(host, port)
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 238, in _init_connection
    self.receive_hello()
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 331, in receive_hello
    packet_type = read_varint(self.fin)
  File "clickhouse_driver/varint.pyx", line 40, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver/bufferedreader.pyx", line 188, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
socket.timeout: timed out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/client.py", line 205, in execute
    self.connection.force_connect()
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 180, in force_connect
    self.connect()
  File "/usr/local/python3/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 277, in connect
    raise err
clickhouse_driver.errors.SocketTimeoutError: Code: 209. None (None:None)

**Comment by xzkostyan** [comment]
https://github.com/mymarilyn/clickhouse-driver/issues/84
