### ISSUE TITLE
A way to disable logging

### ISSUE THREAD

**Issue by tetafro** [mymarilyn/clickhouse-driver#158]
Is there a way to disable logging inside the library? I want to log only from my code, and to disable traces in logs (except from unhandled exception).
But currently I get this
```python
clickhouse = clickhouse_driver.Client(host=host, port=port)
try:
    clickhouse.execute('SELEC 1')
except Exception as e:
    logger.fatal('Failed to execute query: ' + str(e))
```

```
Failed to connect to localhost:9001
Traceback (most recent call last):
  File "/project/venv/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 256, in connect
    return self._init_connection(host, port)
  File "/project/venv/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 226, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/project/venv/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 221, in _create_socket
    raise err
  File "/project/venv/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 212, in _create_socket
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Failed to execute query: Code: 210. Connection refused (None:None)
```

As you can see, there's an error from library along with my own error.

**Comment by xzkostyan** [comment]
Can you paste your logging configuration for `dictConfig`?

**Comment by tetafro** [comment]
Sorry, I should have googled before posting this issue. Looks like this is a common practice for python to define a logger in each module. So I just used this to disable any other loggers:
```python
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': True,
})
```
