### ISSUE TITLE
read_into_buffer time out when insert dataframe

### ISSUE THREAD

**Issue by labbbirder** [mymarilyn/clickhouse-driver#184]
hi there,

when i run `client.execute("insert into my_table values",df.to_dict())`,the program end with`read_into_buffer time out` after a long-time waiting.

error stack:
```
Traceback (most recent call last):

  File "/Users/bbbirder/Documents/svm_test/io_data/clickhouse_source.py", line 44, in <module>
    DataSource({"database":"test"}).store_dataframe(df)

  File "/Users/bbbirder/Documents/svm_test/io_data/clickhouse_source.py", line 35, in store_dataframe
    self.__clt.execute("insert into record values",df.to_dict(),columnar=True)

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/client.py", line 248, in execute
    rv = self.process_ordinary_query(

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/client.py", line 446, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/client.py", line 113, in receive_result
    return result.get_result()

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/numpy/result.py", line 36, in get_result
    for packet in self.packet_generator:

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/client.py", line 129, in packet_generator
    packet = self.receive_packet()

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/client.py", line 143, in receive_packet
    packet = self.connection.receive_packet()

  File "/Users/bbbirder/opt/anaconda3/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 456, in receive_packet
    packet.type = packet_type = read_varint(self.fin)

  File "clickhouse_driver/varint.pyx", line 62, in clickhouse_driver.varint.read_varint

  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one

  File "clickhouse_driver/bufferedreader.pyx", line 237, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer

timeout: timed out
```

i'm using **python3.8**,**clickhouse-driver 0.2.0**,**clickhouse-server docker image:latest**.

by the way,this command runs well `execute("create table...")`

**Comment by labbbirder** [comment]
to_dict with param 'records' resolved this problem.
