### ISSUE TITLE
[Question] socket.timeout - How to pass timeout parameter?

### ISSUE THREAD

**Issue by hashbash** [mymarilyn/clickhouse-driver#196]
How to pass timeout parameter?

Example:
```
from clickhouse_driver import connect
conn = connect(host=conn.host,
                       port=conn.port,
                       user=conn.login,
                       password=conn.password,
                       database=self.schema or conn.schema,
                       settings=dict(socket_timeout=3000000,
                                     send_timeout=3000000,
                                     keepAliveTimeout=3000000))
cursor = conn.cursor()
cursor.execute('optimize table some_table final')
```
Execution fails after 5 minutes:

```
[2021-03-06 10:40:13,000] {taskinstance.py:1145} ERROR - timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/hooks/dbapi_hook.py", line 175, in run
    cur.execute(s)
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/dbapi/cursor.py", line 106, in execute
    **execute_kwargs
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 224, in execute
    columnar=columnar
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 347, in process_ordinary_query
    columnar=columnar)
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 89, in receive_result
    return result.get_result()
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 101, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/client.py", line 115, in receive_packet
    packet = self.connection.receive_packet()
  File "/usr/local/lib64/python3.6/site-packages/clickhouse_driver/connection.py", line 411, in receive_packet
    packet.type = packet_type = read_varint(self.fin)
  File "clickhouse_driver/varint.pyx", line 38, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver/bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver/bufferedreader.pyx", line 188, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
socket.timeout: timed out
```

**Comment by xzkostyan** [comment]
Hi.

The first option: use dsn

```python
from clickhouse_driver import connect

conn = connect(dsn='clickhouse://localhost')
cursor = conn.cursor()

internal_conn = cursor._client.connection
print(internal_conn.connect_timeout, internal_conn.send_receive_timeout, internal_conn.sync_request_timeout)

tuned_conn = connect(dsn='clickhouse://localhost?connect_timeout=11&send_receive_timeout=22&sync_request_timeout=33')
cursor = tuned_conn.cursor()

internal_conn = cursor._client.connection
print(internal_conn.connect_timeout, internal_conn.send_receive_timeout, internal_conn.sync_request_timeout)
```

The second option: use kwargs

```python
from clickhouse_driver import connect

conn = connect(host='localhost')
cursor = conn.cursor()

internal_conn = cursor._client.connection
print(internal_conn.connect_timeout, internal_conn.send_receive_timeout, internal_conn.sync_request_timeout)

tuned_conn = connect(host='localhost', connect_timeout=11, send_receive_timeout=22, sync_request_timeout=33)
cursor = tuned_conn.cursor()

internal_conn = cursor._client.connection
print(internal_conn.connect_timeout, internal_conn.send_receive_timeout, internal_conn.sync_request_timeout)
```

**Comment by hashbash** [comment]
Thank you.

**Comment by lv123123long** [comment]
My code------------------------------------
class Connect:
    def __init__(self, host, port, username, password):
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        # self.database = database_name

        self.conn = connect(host=self.host, user=self.username, password=self.password, port=self.port)

    def exec_cmd(self, sql):
        cursor = self.conn.cursor()
        internal_conn = cursor._client.connection
        print(internal_conn.connect_timeout, internal_conn.send_receive_timeout, internal_conn.sync_request_timeout)
        responce_data = cursor.execute(sql)
        return responce_data

    def close(self):
        self.conn.cursor().fetchall()


new_connect = Connect("10.48.202.134", "29010", "admin", "123131")
tmp_data = new_connect.exec_cmd("CREATE DATABASE huijie_test ON CLUSTER xhraptor;")
print(tmp_data)

And My execution results are as follows-----------------------------


10 300 5
Traceback (most recent call last):
  File "D:/coding/zzz_python/zzz_lvlongxin_common/components_util/ck_util/zzz_tmp.py", line 91, in <module>
    tmp_data = new_connect.exec_cmd("CREATE DATABASE huijie_test ON CLUSTER xhraptor;")
  File "D:/coding/zzz_python/zzz_lvlongxin_common/components_util/ck_util/zzz_tmp.py", line 63, in exec_cmd
    responce_data = cursor.execute(sql)
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\dbapi\cursor.py", line 111, in execute
    response = execute(
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\client.py", line 357, in execute
    rv = self.process_ordinary_query(
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\client.py", line 551, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\client.py", line 188, in receive_result
    return result.get_result()
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\client.py", line 204, in packet_generator
    packet = self.receive_packet()
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\client.py", line 218, in receive_packet
    packet = self.connection.receive_packet()
  File "D:\otherpython\python3810\lib\site-packages\clickhouse_driver\connection.py", line 499, in receive_packet
    packet.type = packet_type = read_varint(self.fin)
  File "clickhouse_driver\varint.pyx", line 62, in clickhouse_driver.varint.read_varint
  File "clickhouse_driver\bufferedreader.pyx", line 55, in clickhouse_driver.bufferedreader.BufferedReader.read_one
  File "clickhouse_driver\bufferedreader.pyx", line 237, in clickhouse_driver.bufferedreader.BufferedSocketReader.read_into_buffer
socket.timeout: timed out
