### ISSUE TITLE
clickhouse_driver.errors.NetworkError: Code: 210

### ISSUE THREAD

**Issue by dmitrii1991** [mymarilyn/clickhouse-driver#211]
**Describe the bug**

Hello everyone. There is a mistake that pisses me off. Here is the code

``` python
from settings import CLICKHOUSE_HOST, CLICKHOUSE_PORT, CLICKHOUSE_USER,  CLICKHOUSE_PASS

class MetaSingleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(MetaSingleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]

class ClickhouseDB(metaclass=MetaSingleton):
    connection = None

    def connect(self):
        if self.connection is None:
            self.connection = Client(
                host=CLICKHOUSE_HOST,
                port=CLICKHOUSE_PORT,
                user=CLICKHOUSE_USER,
                password=CLICKHOUSE_PASS
            )
        return self.connection

if __name__ == "__main__":
    cl = ClickhouseDB()
    cl.connect().execute('SHOW TABLES')

```

here's the traceback

``` python
D:\python\projects_375\mini_projects\venv\Scripts\python.exe D:/python/projects_375/mini_projects/back_ground_tasks/back_ground_tasks/main.py
Failed to connect to http://46.148.XXX.xx:8123
Traceback (most recent call last):
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\connection.py", line 303, in connect
    return self._init_connection(host, port)
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\connection.py", line 268, in _init_connection
    self.socket = self._create_socket(host, port)
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\connection.py", line 224, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "D:\python\Python375\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "D:/python/projects_375/mini_projects/back_ground_tasks/back_ground_tasks/main.py", line 71, in <module>
    cl.connect().execute('SHOW TABLES')
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\client.py", line 233, in execute
    self.connection.force_connect()
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\connection.py", line 202, in force_connect
    self.connect()
  File "D:\python\projects_375\mini_projects\venv\lib\site-packages\clickhouse_driver\connection.py", line 324, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. getaddrinfo failed (http://46.148.XXX.xx:8123)

Process finished with exit code 1

```

link http://46.148.XXX.xx:8123 shows "OK"

The catch is that there are no problems with the library aiochclient 

``` python
from aiochclient import ChClient
from aiohttp import ClientSession

async def clickhouse_create_tb():
    async with ClientSession() as s:
        client = ChClient(
            s,
            url=f'http://{CLICKHOUSE_HOST}:{CLICKHOUSE_PORT}/',
            user=CLICKHOUSE_USER,
            password=CLICKHOUSE_PASS
        )
        for database in ['qwewr', 'wer', 'ewe', 'wq']:
            await client.execute(f"""
                CREATE DATABASE IF NOT EXISTS {database};
            """)

)

```

**Versions**

- clickhouse-driver-0.2.0 
- Python version. 3.7.5

**Comment by pavelmaksimov** [comment]
try through port 9000
