### ISSUE TITLE
Linux Err for clickhouse-driver-0.2.1.tar.gz 

### ISSUE THREAD

**Issue by s348268281** [mymarilyn/clickhouse-driver#229]
**Describe the bug**
i m download clickhouse-driver-0.2.1.tar.gz and tar it
when i use it like:
from clickhouse_driver import Client
CK_CONN_URL = {
    'host': 'myhost',
    'port': myport,
    'database': 'mydatabase'
}
client = Client(**CK_CONN_URL)
sql = 'select count(*) from test'
ans = client.execute(sql)

the err is :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/clickhouse_driver/client.py", line 252, in execute
    self.connection.force_connect()
  File "/xxx/clickhouse_driver/connection.py", line 212, in force_connect
    self.connect()
  File "/xxx/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/xxx/clickhouse_driver/connection.py", line 294, in _init_connection
    self.send_hello()
  File "/xxx/clickhouse_driver/connection.py", line 384, in send_hello
    write_binary_str(self.client_name, self.fout)
  File "/xxx/clickhouse_driver/writer.py", line 16, in write_binary_str
    write_binary_bytes(text, buf)
  File "/xxx/clickhouse_driver/writer.py", line 21, in write_binary_bytes
    buf.write(text)
AttributeError: 'NoneType' object has no attribute 'write'

I read the source code  /clickhouse_driver/connection.py,line 384(write_binary_str(self.client_name, self.fout)),find the self.fout is None,so,who can tell me what to do?

**Versions**

- Version of package with the problem:0.2.1.
- Python version:3.7.

**Comment by xzkostyan** [comment]
Hi.

You should install package from pip or use `pip install clickhouse-driver-0.2.1.tar.gz`. The package installation contains extra steps: compiling cython code. Or just use pypi-wheels.
