### ISSUE TITLE
Inserting a NULL in a LowCardinality(String) should work like in the clickhouse-client

### ISSUE THREAD

**Issue by alexon1234** [mymarilyn/clickhouse-driver#239]
**Describe the bug**

Inserting a NULL in a LowCardinality(String) column using clickhouse-client works fine. It treats the NULL as empty string ("")
But using `clickhouse-driver `  will throw an exception

**To Reproduce**
```

DESKTOP-TNFN1JU.localdomain :) CREATE TABLE checking(test LowCardinality(String)) ENGINE MergeTree() ORDER BY tuple()

CREATE TABLE checking
(
    `test` LowCardinality(String)
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 58bcefee-9021-44de-a38d-b460bfef44d8

Ok.

0 rows in set. Elapsed: 0.026 sec.

DESKTOP-TNFN1JU.localdomain :) INSERT INTO checking VALUES (NULL)

INSERT INTO checking VALUES

Query id: b91ac9ce-efa9-49dd-915e-cc56413894dd

Ok.

1 rows in set. Elapsed: 0.019 sec.

DESKTOP-TNFN1JU.localdomain :) SELECT * FROM checking

SELECT *
FROM checking

Query id: 08f204fa-82f8-41e1-9ff0-278503dabec4

┌─test─┐
│      │
└──────┘

1 rows in set. Elapsed: 0.004 sec.

DESKTOP-TNFN1JU.localdomain :) SELECT * FROM checking WHERE test IS NULL

SELECT *
FROM checking
WHERE isNull(test)

Query id: 7f3390c5-7a5a-473c-8bae-1548ba801c34

Ok.

0 rows in set. Elapsed: 0.004 sec.

DESKTOP-TNFN1JU.localdomain :) SELECT * FROM checking WHERE test = ''

SELECT *
FROM checking
WHERE test = ''

Query id: af19f3e2-a53d-4933-9aa6-d8381b4ef431

┌─test─┐
│      │
└──────┘

1 rows in set. Elapsed: 0.004 sec.
```
```
>>> from clickhouse_driver import Client
>>> client = Client(host='localhost')
>>> client.execute(' CREATE TABLE checking(test LowCardinality(String)) ENGINE MergeTree() ORDER BY tuple()')
[]
>>> client.execute('INSERT INTO checking (test) VALUES', [{'test': None}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/client.py", line 245, in execute
    columnar=columnar
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/client.py", line 472, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/client.py", line 524, in send_data
    self.connection.send_data(block)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 554, in send_data
    self.block_out.write(block)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 39, in write
    self.fout, types_check=block.types_check)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 107, in write_column
    column.write_data(items, buf)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/lowcardinalitycolumn.py", line 97, in _write_data
    self.nested_column.write_data(index, buf)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 81, in _write_data
    self.write_items(prepared, buf)
  File "/.e/lib/python3.7/site-packages/clickhouse_driver/columns/stringcolumn.py", line 19, in write_items
    buf.write_strings(items, encoding=self.encoding)
  File "clickhouse_driver/bufferedwriter.pyx", line 54, in clickhouse_driver.bufferedwriter.BufferedWriter.write_strings
AttributeError: 'NoneType' object has no attribute 'encode'
>>>
```

**Expected behavior**

I expected to behave the same as the clickhouse-client

**Versions**

- Version of package with the problem. clickhouse-driver==0.2.0
- Python version. Python 3.7.10

**Comment by xzkostyan** [comment]
This behavior is controlled by the [input_format_null_as_default](https://clickhouse.tech/docs/ru/operations/settings/settings/#settings-input-format-null-as-default) option and [will not work](https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change-5) by default for ClickHouse sever < 21.x. `clickhouse-client` parses VALUES section from text representation `(NULL)` into binary before sending to server. [It seems](https://github.com/ClickHouse/ClickHouse/pull/17525/files) that format null as default takes place during parsing:

> For text input formats initialize null fields with default values if data type of this field is not nullable

This driver sent data as is (without parsing). This is the main difference between `clickhouse-client` and `clickhouse-driver`.

What's the use case for this feature?

Remember [The Zen of Python](https://www.python.org/dev/peps/pep-0020/): "Explicit is better than implicit."

**Comment by alexon1234** [comment]
I will close this issue because I discover I can use `LowCardinality(Nullable(String))` and it achieve what I want:

- Be able to use LowCardinality even if there is a few null values
- Be able to sort by that column


Thanks for all the help and the driver ❤️
