### ISSUE TITLE
cursor.execute() throw TypeError

### ISSUE THREAD

**Issue by clear2yll** [mymarilyn/clickhouse-driver#278]
**Describe the bug**
Traceback (most recent call last):
  File "/workspace/self/python/demo1/TestClickHouse2.py", line 12, in <module>
    cursor.execute(sql, [(9, 12, 1, 1)])
  File "/workspace/self/python/demo1/venv/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 119, in execute
    self._process_response(response)
  File "/workspace/self/python/demo1/venv/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 322, in _process_response
    rows, columns_with_types = response
TypeError: cannot unpack non-iterable int object

**To Reproduce**
table:
    CREATE TABLE IF NOT EXISTS test.test1
    (
        tenant_id UInt32,
        project_id UInt32,
        _sign Int8,
        _version UInt32
    ) ENGINE = VersionedCollapsingMergeTree(_sign, _version)
    ORDER BY (tenant_id, project_id);
code:
    sql = 'insert into test.test1 (tenant_id, project_id, `_sign`, `_version`) values'
    cursor.execute(sql, [(9, 12, 1, 1)])

**Expected behavior**
insert success

**Versions**
clickhouse-driver Version: 0.2.2
Python 3.8.10

**Comment by xzkostyan** [comment]
Fixed yesterday: https://github.com/mymarilyn/clickhouse-driver/pull/276. Try latest master.

**Comment by xzkostyan** [comment]
Published in 0.2.3.
