### ISSUE TITLE
INSERT high precision floats into lower precision decimal column fails

### ISSUE THREAD

**Issue by joelynch** [mymarilyn/clickhouse-driver#289]
Since 0.2.3 get an error with the following code

```python
>>> client.execute('''CREATE TABLE IF NOT EXISTS dec_test (id Integer, val Decimal(9, 4)) ENGINE = MergeTree order by id;''')
>>> client.execute('INSERT INTO dec_test VALUES', [(1, 3.14159265358979323846264338327)], types_check=True)
Traceback (most recent call last):
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 130, in write_column
    column.write_data(items, buf)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/decimalcolumn.py", line 74, in _write_data
    super(DecimalColumn, self)._write_data(items, buf)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 80, in _write_data
    prepared = self.prepare_items(items)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 64, in prepare_items
    check_item(x)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/decimalcolumn.py", line 27, in check_item
    raise ColumnTypeMismatchException(value)
clickhouse_driver.columns.exceptions.ColumnTypeMismatchException: 3.141592653589793

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/client.py", line 293, in execute
    columnar=columnar
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/client.py", line 510, in process_insert_query
    types_check=types_check, columnar=columnar)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/client.py", line 562, in send_data
    self.connection.send_data(block)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 576, in send_data
    self.block_out.write(block)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 39, in write
    self.fout, types_check=block.types_check)
  File "/Users/joe.lynch/Library/Caches/pypoetry/virtualenvs/tern-kEo3BQPi-py3.7/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 136, in write_column
    column_spec, type(e.args[0]), e.args[0], column_name
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Expected Decimal(9, 4) got <class 'float'>: 3.141592653589793 for column "val".
```

Is this behaviour too strict?  The previous behaviour where float precision was just truncated seemed fine to me.

**Comment by xzkostyan** [comment]
Yes, this is too strict.
