### ISSUE TITLE
The error message is not expected when the database does not exist

### ISSUE THREAD

**Issue by Littlecowherd** [mymarilyn/clickhouse-driver#308]
When I try to connect to a database that doesn't exist, I want a clear error message like: "Code: 81. DB::Exception: Database qt doesn't exist". This is true in most cases, but sometimes I got "BrokenPipeError: [Errno 32] Broken pipe"

Here is a mini case
```python
from clickhouse_driver import Client
 
client = Client(host='127.0.0.1',   # in localhost
                port=9000,
                user='default',
                password='',
                database='qt',   # a database that does not exist
                )
try:
    resp = client.execute('select 1')
except Exception as e:
    print(type(e), str(e)[:50])
finally:
    client.disconnect()
```

Run this code multiple times， here is the output
```plain
while true; do python ch.py; sleep 0.5; done
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
<class 'clickhouse_driver.errors.ServerException'> Code: 81.
DB::Exception: Database qt doesn't exist
Error on socket shutdown: [Errno 107] Transport endpoint is not connected
<class 'BrokenPipeError'> [Errno 32] Broken pipe
```
And here is the detailed error message where BrokenPipeError appears
```plain
Error on socket shutdown: [Errno 107] Transport endpoint is not connected
2022-05-10 15:18:27.639 | ERROR    | __main__:<module>:12 - [Errno 32] Broken pipe
Traceback (most recent call last):

> File "test.py", line 10, in <module>
    resp = client.execute('select 1')
           │      └ <function Client.execute at 0x7f1016b155e0>
           └ <clickhouse_driver.client.Client object at 0x7f10243dea30>

  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/client.py", line 296, in execute
    rv = self.process_ordinary_query(
         │    └ <function Client.process_ordinary_query at 0x7f1016b15940>
         └ <clickhouse_driver.client.Client object at 0x7f10243dea30>
  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/client.py", line 480, in process_ordinary_query
    self.connection.send_external_tables(external_tables,
    │    │          │                    └ None
    │    │          └ <function Connection.send_external_tables at 0x7f1016b11040>
    │    └ <clickhouse_driver.connection.Connection object at 0x7f10243158e0>
    └ <clickhouse_driver.client.Client object at 0x7f10243dea30>
  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 641, in send_external_tables
    self.send_data(RowOrientedBlock())
    │    │         └ <class 'clickhouse_driver.block.RowOrientedBlock'>
    │    └ <function Connection.send_data at 0x7f1016b10e50>
    └ <clickhouse_driver.connection.Connection object at 0x7f10243158e0>
  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 576, in send_data
    self.block_out.write(block)
    │    │               └ <clickhouse_driver.block.RowOrientedBlock object at 0x7f10156c76a0>
    │    └ None
    └ <clickhouse_driver.connection.Connection object at 0x7f10243158e0>
  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 41, in write
    self.finalize()
    │    └ <function BlockOutputStream.finalize at 0x7f1016b08ee0>
    └ <clickhouse_driver.streams.native.BlockOutputStream object at 0x7f10156a8f70>
  File "/usr/local/qingteng/python3.8/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 44, in finalize
    self.fout.flush()
    │    │    └ <method 'flush' of 'clickhouse_driver.bufferedwriter.BufferedWriter' objects>
    │    └ <clickhouse_driver.bufferedwriter.BufferedSocketWriter object at 0x7f10156bfe00>
    └ <clickhouse_driver.streams.native.BlockOutputStream object at 0x7f10156a8f70>
  File "clickhouse_driver/bufferedwriter.pyx", line 46, in clickhouse_driver.bufferedwriter.BufferedWriter.flush
  File "clickhouse_driver/bufferedwriter.pyx", line 127, in clickhouse_driver.bufferedwriter.BufferedSocketWriter.write_into_stream

BrokenPipeError: [Errno 32] Broken pipe
```

**Expected behavior**
Find out why this error message appears and get correct error messages(Database qt doesn't exist) all the time. 

**Versions**
clickhouse-driver version: 0.2.3
Python version: 3.8.10
ClickHouse server version 21.11.11.1 (official build).

**Comment by xzkostyan** [comment]
Need extra info to reproduce the problem.

**Comment by Littlecowherd** [comment]
Sorry, the clickhouse server I used was destroyed. We will have a new server when the next iteration of the project begins, I will check clickhouse-server log if the problem reappears, THANKS for your help.
