### ISSUE TITLE
deleting the "default" database kills the connector

### ISSUE THREAD

**Issue by gauvins2** [mymarilyn/clickhouse-driver#309]
**Describe the bug**
After deleting the "default" database
**To Reproduce**
     from clickhouse_driver import Client
     cx = Client('localhost')
     theResult = cx.execute(theQuery)

    (any query will do)

**Expected behavior**
   data should be returned.
**Versions**
   CH-driver 0.2.[3-4]
   CH 22.4.5.9
   Python 3.10.4

Error on socket shutdown: [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 296, in execute
    rv = self.process_ordinary_query(
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 482, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 143, in receive_result
    return result.get_result()
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 159, in packet_generator
    packet = self.receive_packet()
  File "/home/gauvins/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 176, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 81.
DB::Exception: Database default doesn't exist. Stack trace:

**Comment by xzkostyan** [comment]
Current behaviour is correct. `clickhouse-client` has the same:

```
$ clickhouse-client --query 'select 1'
1
```

```
$ clickhouse-client -d not-existent-database --query 'select 1'
Received exception from server (version 22.4.3):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Database `not-existent-database` doesn't exist. (UNKNOWN_DATABASE)
(query: select 1)
```

**Comment by gauvins2** [comment]
Clickhouse-client was working on my system (the query specifies a database. Will bork if no database is specified)

**Comment by xzkostyan** [comment]
I see. It would be nice if you could post full motivation in expected behaviour. Including `clickhouse-client` examples and particular queries.

**Comment by gauvins2** [comment]
1. A query like "SELECT COUNT() FROM myDB.myTable" should execute even if the [default] db has been deleted

motivation is simply that I deleted [default] because I like clean environments. Took me a while to figure out why the driver didn't work. In the meantime I've re-created an empty default DB

**Comment by xzkostyan** [comment]
Fix was merged into master.
