### ISSUE TITLE
Boolen data type upload problem

### ISSUE THREAD

**Issue by MIracleyin** [mymarilyn/clickhouse-driver#331]
**Describe the bug**
Hi, I upload some data to clickhouse by clickhouse-driver. And my data types include "Boolen", the python script is run successfully. But the data in my database is not correct.

The error as below:

<failed to load>
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Parse exception: ByteFragment{[116981165<TAB>\N<TAB>\N<TAB>\N<TAB>\N<TAB>1619177543,2011474749<TAB>['Physics']<TAB>10.1016/0370-2693(86)91382-1<TAB>Multiplicities in a QCD-motivated description of very high energy particle interactions<TAB>[{'first':['Thomas'],'middle':['K.'],'last':['Gaisser']},{'first':['Francis'],'middle':[],'last':['Halzen']},{'first':['A.'],'middle':['D.'],'last':['Martin']},{'first':['C.'],'middle':['J.'],'last':['Maxwell']}]<TAB>\N<TAB>Physics Letters B<TAB>1986<TAB>Abstract At high energy a significant fraction of the cross section consists of events containing QCD jets. The rapid increase of the rate of these high multiplicity events with energy naturally results in a breakdown of KNO scaling. At the presently available collider energies the violations of KNO scaling found in such a model are very similar to those resulting from the negative binomial parametrization of the multiplicity distribution.<TAB>[]<TAB>[]<TAB>\N<TAB>\N<TAB>https://api.semanticscholar.org/CorpusID:116981165<TAB>true<TAB>\N<TAB>\N<TAB>true<TAB>\N<TAB>2022-08-23 19:05:41.389628<TAB>2022-08-23 19:05:41.389628], start=930, len=4}; ClickHouse exception, message: Error parsing 'true' as java.lang.Integer; For input string: "true"
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:648)
	in JdbcHelperImpl.getObject(JdbcHelperImpl.java:323)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, message: Error parsing 'true' as java.lang.Integer; For input string: "true"
	at ru.yandex.clickhouse.response.parser.ClickHouseValueParser$ClickHouseValueParserFunctionWrapper.parse(ClickHouseValueParser.java:243)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:749)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:603)
	... 20 more
Caused by: java.lang.NumberFormatException: For input string: "true"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:957)
	at java.base/java.lang.Integer.decode(Integer.java:1436)
	at ru.yandex.clickhouse.response.parser.ClickHouseValueParser$ClickHouseValueParserFunctionWrapper.parse(ClickHouseValueParser.java:240)
	... 22 more

**To Reproduce**
Minimal piece of Python code that reproduces the problem.
CREATE TABLE IF NOT EXISTS paper
        (
            has_inbound_citations   Nullable(Bool),
            has_outbound_citations  Nullable(Bool),
        )
        engine = Memory

INSERT INTO paper
has_inbound_citations,has_outbound_citations
VALUES

**Expected behavior**
It seems to be 'true' or 'false' in the database but given errors text.

**Versions**

- Version of package with the problem.
- ClickHouse server version. Version can be obtained by running `SELECT version()` query.
- Python version.

python 3.10
clickhouse-driver 0.2.4
SELECT version()

**Comment by xzkostyan** [comment]
It seems that exception is for java package. This project is written in python.

Does clickhouse-client work fine?

**Comment by MIracleyin** [comment]
Yes, It is quite weird.
I writing a python script to create a database and insert data into it.
Is the python's type boolean can't be dealt with? But I noticed in your document here https://clickhouse-driver.readthedocs.io/en/latest/types.html#:~:text=%2C%20T.-,Bool,-%C2%B6.
could I make a Minimum Work Example for you?
