### ISSUE TITLE
execute wait long time

### ISSUE THREAD

**Issue by liyongcun** [mymarilyn/clickhouse-driver#35]
[root@lyc tmp]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from clickhouse_driver import Client
>>> client = Client('192.168.133.2',18123,'client_report','admin','************',insert_block_size=1)
>>> client.execute('SHOW TABLES')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/client.py", line 159, in execute
    self.connection.force_connect()
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/connection.py", line 122, in force_connect
    self.connect()
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/connection.py", line 188, in connect
    self.receive_hello()
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/connection.py", line 263, in receive_hello
    packet_type = read_varint(self.fin)
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/reader.py", line 29, in read_varint
    i = _read_one(f)
  File "/usr/lib/python2.6/site-packages/clickhouse_driver/reader.py", line 14, in _read_one
    c = f.read(1)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
KeyboardInterrupt
>>>

**Comment by xzkostyan** [comment]
It seems that you're using forwarded HTTP port (18123) (original is 8123). Use TCP (9000) instead. https://github.com/mymarilyn/clickhouse-driver#client-parameters
