### ISSUE TITLE
How to properly handle the ConnectionRefusedError exception?

### ISSUE THREAD

**Issue by iBrokeYourGui** [mymarilyn/clickhouse-driver#357]
When i create session, regardless of the result - ClickHouse will return an abstract session object.
`session = Client(host=config.CH_HOST, port=config.CH_PORT, database=config.CH_DATABASE, user=config.CH_USER, password=config.CH_PASS)`

It useless for me, and next i do: `session.execute('Select 1')`, for catch exceptions.

In this case we well receive 2 exception: **NetworkError**, **ConnectionRefusedError**

The problem is that in the try except block I can't catch ConnectionRefusedError, cause it is processed before the request is run. 
(it print in stdOut forcibly, if i correctly read source code)

And the question is **how a can processed it and do not pull trace into log**?

**Comment by xzkostyan** [comment]
You should handle `clickhouse_driver.errors.NetworkError`. You can use [context manager](https://gist.github.com/simon-weber/7853144) or configure proper logging level if you want to mute warning messages about this undesired behaviour.

**Comment by iBrokeYourGui** [comment]
> You should handle `clickhouse_driver.errors.NetworkError`. You can use [context manager](https://gist.github.com/simon-weber/7853144) or configure proper logging level if you want to mute warning messages about this undesired behaviour.

Tanks 4 answer! 
But it not work. Here is a little synth for u. 
When CH container down i have many garbage in trace. 


```python
import sys
import logging

from clickhouse_driver import Client
from clickhouse_driver.errors import NetworkError

log = logging.getLogger('connect_to_ClickHouse')
logging.basicConfig(
    level="INFO",
    format=" [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stdout
)


def connect_clickhouse():
    session = Client(host="localhost", port="9000", database="default",
                     user="default", password="")
    try:
        session.execute('Select 1')
        log.info('Connect to ClickHouse server')
        return session
    except NetworkError as exc:
        log.exception(exc)
        return None


def main():
    connect_clickhouse()


if __name__ == '__main__':
    main()
```

**Comment by xzkostyan** [comment]
This should work

```python
import sys
import logging
from contextlib import contextmanager

from clickhouse_driver import Client
from clickhouse_driver.errors import NetworkError

log = logging.getLogger('connect_to_ClickHouse')
logging.basicConfig(
    level="INFO",
    format=" [%(levelname)s] %(name)s: %(message)s",
    stream=sys.stdout
)


@contextmanager
def logging_disabled(logger, level):
    # Taken from logging.disable
    logger.manager.disable = level
    logger.manager._clear_cache()
    yield
    logger.manager.disable = logging.NOTSET
    logger.manager._clear_cache()


def connect_clickhouse():
    session = Client(host="localhost", port="9000")
    
    try:
        with logging_disabled(logging.getLogger('clickhouse_driver.connection'), 'WARN'):
          print(session.execute('select 1'))
          log.info('Connect to ClickHouse server')
          return session
    except NetworkError as exc:
        log.exception(exc)
        return None


def main():
    connect_clickhouse()


if __name__ == '__main__':
    main()
```

**Comment by iBrokeYourGui** [comment]
No, it helped a little.
WARNING disabled.  
NetworkError- still stay in in trace 

is it necessary, do such hard processing? )

**Comment by xzkostyan** [comment]
You can remove `log.exception(exc)` from `except` block and there will be no logs.

**Comment by iBrokeYourGui** [comment]
This is driver behavior. 

`Traceback (most recent call last):
File ".../clickhouse_driver/connection.py", line 342, in connect.
return self._init_connection(host, port).
File ".../clickhouse_driver/connection.py", line 306, in _init_connection
self.socket = self._create_socket(host, port)
File "/.../clickhouse_driver/connection.py", line 278, in _create_socket
raise err
File ".../clickhouse_driver/connection.py", line 269, in _create_socket
sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused`

Yea, the only way is remove warnings. But it's not good idea ) 
Well, let it be....

**Comment by xzkostyan** [comment]
What's wrong with this behavior? You have connection error. This is not expected situation and user should be notified about it.

**Comment by iBrokeYourGui** [comment]
Поведение корректное. 
Мне просто не понятно, зачем принудительно в stdout писать трейс ConnectionRefusedError, когда и так понятно что у нас NetworkError из за отсутствия подключения к базе. 
Таким образом я не могу обработать ConnectionRefusedError в блоке try except (так как исключение обрабатывается самим драйвером) и получаю мусор в логах. 
Отключать варнинги я не могу,  так как ошибки в проекте могут возникнуть не только в точке подключения.

**Comment by xzkostyan** [comment]
1) Мы сохраняем оригинальный стектрейс и ошибку чтобы было понятно, где именно созникла проблема. По исключению, которое мы кидаем в ходе обработки текущего, не понятно где именно произошла ошибка в сокетах.
2) Это необходимо, когда мы используем опцию `alt_hosts` чтобы в логах пользователю дать понять, что с одним из соединений проблема:

```
In [1]: from clickhouse_driver import Client
   ...: client = Client('localhost1', alt_hosts='localhost')

In [2]: client.execute('select 1')
Failed to connect to localhost1:9000
Traceback (most recent call last):
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 342, in connect
    return self._init_connection(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 306, in _init_connection
    self.socket = self._create_socket(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 257, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "~/.pyenv/versions/3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Out[2]: [(1,)]

In [3]: client.execute('select 1')
Out[3]: [(1,)]

In [4]: client.execute('select 1')
Out[4]: [(1,)]
```

При этом если все попытки коннектов отвалились, то кидается именно исключение:

```
In [5]: from clickhouse_driver import Client
   ...: client = Client('localhost1', alt_hosts='localhost2')

In [6]: client.execute('select 1')
Failed to connect to localhost1:9000
Traceback (most recent call last):
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 342, in connect
    return self._init_connection(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 306, in _init_connection
    self.socket = self._create_socket(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 257, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "~/.pyenv/versions/3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
Failed to connect to localhost2:9000
Traceback (most recent call last):
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 342, in connect
    return self._init_connection(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 306, in _init_connection
    self.socket = self._create_socket(host, port)
  File "~/work/clickhouse-driver/clickhouse_driver/connection.py", line 257, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "~/.pyenv/versions/3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
---------------------------------------------------------------------------
NetworkError                              Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 client.execute('select 1')

File ~/work/clickhouse-driver/clickhouse_driver/client.py:347, in Client.execute(self, query, params, with_column_types, external_tables, query_id, settings, types_check, columnar)
    304 """
    305 Executes query.
    306 
   (...)
    342               and types.
    343 """
    345 start_time = time()
--> 347 with self.disconnect_on_error(query, settings):
    348     # INSERT queries can use list/tuple/generator of list/tuples/dicts.
    349     # For SELECT parameters can be passed in only in dict right now.
    350     is_insert = isinstance(params, (list, tuple, types.GeneratorType))
    352     if is_insert:

File ~/.pyenv/versions/3.8.12/lib/python3.8/contextlib.py:113, in _GeneratorContextManager.__enter__(self)
    111 del self.args, self.kwds, self.func
    112 try:
--> 113     return next(self.gen)
    114 except StopIteration:
    115     raise RuntimeError("generator didn't yield") from None

File ~/work/clickhouse-driver/clickhouse_driver/client.py:291, in Client.disconnect_on_error(self, query, settings)
    288 @contextmanager
    289 def disconnect_on_error(self, query, settings):
    290     try:
--> 291         self.establish_connection(settings)
    293         yield
    295         self.track_current_database(query)

File ~/work/clickhouse-driver/clickhouse_driver/client.py:278, in Client.establish_connection(self, settings)
    276     self.connection = self.get_connection()
    277     self.make_query_settings(settings)
--> 278     self.connection.force_connect()
    279     self.last_query = QueryInfo()
    281 except (errors.SocketTimeoutError, errors.NetworkError):

File ~/work/clickhouse-driver/clickhouse_driver/connection.py:235, in Connection.force_connect(self)
    232 self.check_query_execution()
    234 if not self.connected:
--> 235     self.connect()
    237 elif not self.ping():
    238     logger.warning('Connection was closed, reconnecting.')

File ~/work/clickhouse-driver/clickhouse_driver/connection.py:363, in Connection.connect(self)
    360     self.hosts.rotate(-1)
    362 if err is not None:
--> 363     raise err

NetworkError: Code: 210. Temporary failure in name resolution (localhost2:9000)
```

Обрабатывать эту ситуацию отдельно если `alt_hosts` не задано не вижу смысла. Потому как это порождает нестандартное поведение в зависимости от разчных параметров.
