### ISSUE TITLE
Memory Overflow

### ISSUE THREAD

**Issue by brunoalano** [mymarilyn/clickhouse-driver#37]
I'm running Clickhouse on production, using the `asyncio` wrapper. But sometimes I get a issue when inserting into database.

```
Job processing failed
job: <Job coro=<<coroutine object user_events_producer at 0x7f39382c1fc0>>>
Traceback (most recent call last):
  File "./app.py", line 189, in user_events_producer
    [e.data for e in events_queue]
  File "/usr/local/lib/python3.6/site-packages/aioch/client.py", line 92, in execute
    **kwargs)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 159, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 124, in force_connect
    elif not self.ping():
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 303, in ping
    packet_type = read_varint(self.fin)
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/reader.py", line 29, in read_varint
    i = _read_one(f)
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/reader.py", line 14, in _read_one
    c = f.read(1)
info ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL
Job processing failed
job: <Job coro=<<coroutine object user_events_producer at 0x7f3939175308>>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 169, in execute
    types_check=types_check
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 237, in process_insert_query
    sample_block = self.receive_sample_block()
  File "/usr/local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 251, in receive_sample_block
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 101.
DB::NetException. DB::NetException: Unexpected packet Query received from client. Stack trace:
ingestion-server
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x15) [0x84eb065]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x21) [0x2ccbe01]
2. /usr/bin/clickhouse-server(DB::TCPHandler::receivePacket()+0x22e) [0x2cdb7de]
3. /usr/bin/clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x1c2) [0x2cdbb42]
4. /usr/bin/clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x205) [0x2cdbee5]
5. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x476) [0x2cdc566]
6. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2a) [0x2cdd3ba]
7. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xe) [0x86d53de]
8. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x169) [0x86d57b9]
9. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x76) [0x8776976]
10. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x37) [0x8772b87]
11. /usr/bin/clickhouse-server() [0x8dd397e]
12. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76da) [0x7f650da8d6da]
13. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3e) [0x7f650d21488e]
ingestion-server
```

I don't know if the issue is the server or the client.

**Comment by xzkostyan** [comment]
Hi, @brunoalano!

Can you provide more details about your query/server version/requirements.txt?

Example of `aioch` using and clickhouse logs will be also helpful.

**Comment by brunoalano** [comment]
@xzkostyan I was using `aioch` inside a Websocket server, where I was managing connection to the database in some servers receiving about 100K req/s.

I actually changed Clickhouse to other solution, using Google Datastore + Postgres instead, since I was having instability from Clickhouse

**Comment by kirthegrave** [comment]
Hi there! I met same issue but with the "select" query.
I have aiohttp view with query execution. And when i call this view several times with short time interval (previous view calls isn't complete) then i get this exception. But if i call this view only one time the query will be completed correctly without exceptions.

Usages:
python 3.7

requirements:
aiohttp==3.3.2
clickhouse-driver==0.0.10
aioch==0.0.1

```
  File "/usr/local/lib/python3.7/site-packages/aioch/client.py", line 92, in execute
    **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 159, in execute
    self.connection.force_connect()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 124, in force_connect
    elif not self.ping():
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 303, in ping
    packet_type = read_varint(self.fin)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/reader.py", line 29, in read_varint
    i = _read_one(f)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/reader.py", line 14, in _read_one
    c = f.read(1)
ValueError: PyMemoryView_FromBuffer(): info->buf must not be NULL
```

**Comment by xzkostyan** [comment]
@kirthegrave does problem appear with latest clickhouse-driver?

**Comment by kirthegrave** [comment]
I installed last version of clickhouse-driver (0.0.18) and got some different errors.
```
File "/usr/local/lib/python3.7/site-packages/aioch/client.py", line 92, in execute
  **kwargs)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 191, in execute
  self.connection.force_connect()
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 168, in force_connect
  elif not self.ping():
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 367, in ping
  raise errors.UnexpectedPacketFromServerError(msg)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server clickhouse:9000 (expected Pong, got ProfileInfo)
```

```
File "/usr/local/lib/python3.7/site-packages/aioch/client.py", line 92, in execute
  **kwargs)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 191, in execute
  self.connection.force_connect()
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 168, in force_connect
  elif not self.ping():
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 378, in ping
  return False
File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
  next(self.gen)
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 527, in timeout_setter
  self.socket.settimeout(old_timeout)
AttributeError: 'NoneType' object has no attribute 'settimeout'
```

```
File "/usr/local/lib/python3.7/site-packages/aioch/client.py", line 92, in execute
  **kwargs)
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 209, in execute
  columnar=columnar
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 327, in process_ordinary_query
  columnar=columnar)
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 80, in receive_result
  return result.get_result()
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/result.py", line 47, in get_result
  for packet in self.packet_generator:
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 92, in packet_generator
  packet = self.receive_packet()
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 106, in receive_packet
  packet = self.connection.receive_packet()
File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 416, in receive_packet
  packet_type, self.get_description()
clickhouse_driver.errors.UnknownPacketFromServerError: Code: 100. Unknown packet 4 from server clickhouse:9000
```

Should I create another issue?

**Comment by xzkostyan** [comment]
@kirthegrave well, maybe. Please, add minimal example of code that reproduces your issue.
