### ISSUE TITLE
Tuple support

### ISSUE THREAD

**Issue by NetBUG** [mymarilyn/clickhouse-driver#38]
I can't return unique combinations of two columns (e.g. `src` and `dst`). 
Executing a query with `SELECT DISTINCT(field1, field2)` causes the following error when returning data from Clickhouse:

```SELECT DISTINCT (src, dst) as key FROM samples WHERE timestamp > now() - 9600;
Traceback (most recent call last):
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/columns/service.py", line 56, in get_column_by_spec
cls = column_by_type[spec]
KeyError: 'Tuple(String, String)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./cronapp.py", line 71, in
run(period=period)
File "./cronapp.py", line 52, in run
data = get_conn_list(period=period)
File "./cronapp.py", line 21, in get_conn_list
return client.execute(query)
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 176, in execute
types_check=types_check, columnar=columnar
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 227, in process_ordinary_query
columnar=columnar)
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 75, in receive_result
self.receive_no_progress_result(result, columnar)
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 102, in receive_no_progress_result
packet = self.receive_packet()
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/client.py", line 133, in receive_packet
packet = self.connection.receive_packet()
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 331, in receive_packet
packet.block = self.receive_data()
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/connection.py", line 394, in receive_data
block = self.block_in.read()
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/streams/native.py", line 77, in read
column = read_column(column_type, n_rows, self.fin)
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/columns/service.py", line 64, in read_column
column = get_column_by_spec(column_spec)
File "/home/netbug/.local/lib/python3.6/site-packages/clickhouse_driver/columns/service.py", line 60, in get_column_by_spec
raise errors.UnknownTypeError('Unknown type {}'.format(e.args[0]))
clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type Tuple(String, String)```

**Comment by xzkostyan** [comment]
Hi.

Yep, that's it. Tuple type is not implemented yet. Any PR are appreciated.

**Comment by xzkostyan** [comment]
Tuple type is supported by [latest master](https://github.com/mymarilyn/clickhouse-driver/commit/9aefda5c3736d8ee9c0ba19f2901dad8bb31277b).

**Comment by revan57** [comment]
> Tuple type is supported by [latest master](https://github.com/mymarilyn/clickhouse-driver/commit/9aefda5c3736d8ee9c0ba19f2901dad8bb31277b).

Hi, there is an exception when i try to pass tuple in groupArray:

select groupArray(tuple(1,2,3)); 
`File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 218, in execute
              columnar=columnar
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 341, in process_ordinary_query
              columnar=columnar)
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 83, in receive_result
              return result.get_result()
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/result.py", line 48, in get_result
              for packet in self.packet_generator:
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 95, in packet_generator
              packet = self.receive_packet()
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 109, in receive_packet
              packet = self.connection.receive_packet()
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 412, in receive_packet
              packet.block = self.receive_data()
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/connection.py", line 480, in receive_data
              return self.block_in.read()
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/streams/native.py", line 75, in read
              self.fin)
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/service.py", line 89, in read_column
              return column.read_data(n_items, buf)
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 61, in read_data
              return self._read(rows, buf)
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/arraycolumn.py", line 174, in _read
              nulls_map=nulls_map[prev_offset:prev_offset + size]
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 95, in _read_data
              items = self.read_items(n_items, buf)
            File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/columns/base.py", line 107, in read_items
              raise NotImplementedError
          NotImplementedError`

**Comment by luka-papez** [comment]
For those still running into this issue:
a quick workaround is to wrap the resulting `Tuple` in the query into a `toString` call and then call `ast.literal_eval` on that thing from the Python side.

**Comment by xzkostyan** [comment]
@revan57 fixed in master: https://github.com/mymarilyn/clickhouse-driver/commit/60171119286edcd2555ae8ed294830174bcd8b3d.

**Comment by xzkostyan** [comment]
Version 0.1.4 with `Tuple` support is released.
