### ISSUE TITLE
Using a specific name in the parameter substitutions leads to a ServerException.

### ISSUE THREAD

**Issue by gtors** [mymarilyn/clickhouse-driver#396]
**Describe the bug**

- `limit` in params lead to ServerException. 
- using `limit2` instead of `limit` eliminates  the exception 

```
from clickhouse_driver import Client

client = Client("localhost")
client.execute("SELECT 1 LIMIT %(limit)d", params={"limit": 1})
```

```
Traceback (most recent call last):
  File "/tmp/wtf/t.py", line 4, in <module>
    client.execute("SELECT 1 LIMIT %(limit)d", {"limit": 1})
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/client.py", line 362, in execute
    rv = self.process_ordinary_query(
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/client.py", line 588, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types, columnar=columnar)
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/client.py", line 184, in receive_result
    return result.get_result()
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/client.py", line 198, in packet_generator
    packet = self.receive_packet()
  File "/home/user/.cache/pypoetry/virtualenvs/wtf-mmF0-zbx-py3.10/lib/python3.10/site-packages/clickhouse_driver/client.py", line 215, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 26.
DB::ParsingException. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '1'. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d627a in /usr/bin/clickhouse
1. ? @ 0x792d613 in /usr/bin/clickhouse
2. void DB::readQuotedStringInto<false, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::ReadBuffer&) @ 0x791cc5e in /usr/bin/clickhouse
3. DB::TCPHandler::receiveQuery() @ 0x12f1d4e6 in /usr/bin/clickhouse
4. DB::TCPHandler::receivePacket() @ 0x12f139a7 in /usr/bin/clickhouse
5. DB::TCPHandler::runImpl() @ 0x12f0c09a in /usr/bin/clickhouse
6. DB::TCPHandler::run() @ 0x12f20839 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x159b27af in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x159b4b3b in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x15b700d2 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x15b6d85d in /usr/bin/clickhouse
11. ? @ 0x7f34f2167609 in ?
12. clone @ 0x7f34f208c133 in ?
```

**To Reproduce**
```
from clickhouse_driver import Client

client = Client("localhost")
client.execute("SELECT 1 LIMIT %(limit)d", params={"limit": 1})
```

**Expected behavior**
It should be possible to specify any name for the placeholder

**Versions**

- clickhouse_driver v0.2.6
- ClickHouse v22.11.1.1360
- Python v3.10

**Comment by gtors** [comment]
For some reason params for substitution also passed to `send_query`:

https://github.com/mymarilyn/clickhouse-driver/blob/18f28c633c89ee2225928be53dfda8a39e8f00ca/clickhouse_driver/client.py#L579-L584

And inside `send_query` it used to write settings:

https://github.com/mymarilyn/clickhouse-driver/blob/18f28c633c89ee2225928be53dfda8a39e8f00ca/clickhouse_driver/connection.py#L704-L709

**Comment by gtors** [comment]
there is no such error in version 0.2.5

**Comment by xzkostyan** [comment]
I think this duplicates #376
