### ISSUE TITLE
Unexpected 'driver'

### ISSUE THREAD

**Issue by hekto324** [mymarilyn/clickhouse-driver#411]
I hope the translation of my text is correct.

Hi all.

I have a problem with the clickhouse-driver, clickhouse-pool and django-clickouse-backed packages. The latest versions are used. As far as I understand, the problem is that when connecting to the database, a driver is generated in the Connection (clickhouse-driver) class, which clickhouse-backend does not see. Please tell me how this can be fixed?

I did not touch the clickhouse-backend and clickhouse-driver root folders.

clickhouse-pool==0.5.3
django-clickhouse-backend==1.1.6
clickhouse-driver==0.2.6
infi.clickhouse-orm==2.1.3

Bug: root@520015ac72a2:/project# python manage.py migrate --database clickhouse
Traceback (most recent call last):
File "/project/manage.py", line 22, in
main()
File "/project/manage.py", line 18, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.12/site-packages/django/core/management/init.py", line 442, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.12/site-packages/django/core/management/init.py", line 436, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
output = self.handle(*args, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 106, in wrapper
res = handle_func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 117, in handle
executor = MigrationExecutor(connection, self.migration_progress_callback)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/migrations/executor.py", line 18, in init
self.loader = MigrationLoader(self.connection)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 58, in init
self.build_graph()
File "/usr/local/lib/python3.12/site-packages/django/db/migrations/loader.py", line 235, in build_graph
self.applied_migrations = recorder.applied_migrations()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/migrations/recorder.py", line 89, in applied_migrations
if self.has_table():
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/patch/migrations.py", line 69, in has_table
with self.connection.cursor() as cursor:
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor
return self._cursor()
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor
self.ensure_connection()
File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection
self.connect()
File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
self.connection = self.get_new_connection(conn_params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/backend/base.py", line 215, in get_new_connection
conn = Database.connect(**conn_params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/driver/init.py", line 38, in connect
return Connection(
^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/driver/connection.py", line 115, in init
self.pool = ClickhousePool(
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/driver/pool.py", line 11, in init
super().init(**kwargs)
File "/usr/local/lib/python3.12/site-packages/clickhouse_pool/pool.py", line 54, in init
self._connect()
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/driver/pool.py", line 18, in _connect
client = Client(**self.connection_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/clickhouse_backend/driver/client.py", line 20, in init
super().init(*args, **kwargs)
File "/usr/local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 130, in init
self.connections = deque([Connection(*args, **kwargs)])
^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Connection.__init()__ got an unexpected keyword argument 'driver'

**Comment by hekto324** [comment]
@xzkostyan Прошу помочь
