### ISSUE TITLE
Invalid argument error when reading datetime data

### ISSUE THREAD

**Issue by IlluvatarEru** [mymarilyn/clickhouse-driver#448]
**Describe the bug**
I am reading data from a table, specifically getting the `distinct timestamp`.
The type of that column is `DateTime64(6)`.

I am receiving the below error:
```
ERROR:root:MEV-Q CH query failed: select distinct timestamp from db.table where  timestamp > '2024-07-29' 
 with exception:
[Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\driver\client.py", line 193, in query
    return self._query_with_context(query_context)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\driver\httpclient.py", line 222, in _query_with_context
    query_result = self._transform.parse_response(byte_source, context)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\driver\transform.py", line 68, in parse_response
    first_block = get_block()
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\driver\transform.py", line 50, in get_block
    column = col_type.read_column(source, num_rows, context)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\datatypes\base.py", line 143, in read_column
    return self.read_column_data(source, num_rows, ctx)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\datatypes\base.py", line 158, in read_column_data
    column = self._read_column_binary(source, num_rows, ctx)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\datatypes\temporal.py", line 179, in _read_column_binary
    return self._read_binary_tz(column, active_tz)
  File "C:\Users\user\anaconda3\lib\site-packages\clickhouse_connect\datatypes\temporal.py", line 189, in _read_binary_tz
    dt_sec = dt_from(seconds, tz_info)
OSError: [Errno 22] Invalid argument
```

Note that running the exact same query from the CH client directly works fine.
Note: the min timestamp in that table is: `1970-01-01 01:00:00.000000` not sure if that could create an issue.

**To Reproduce**
I am really just creating a client and running the select query: `select distinct timestamp from db.table where  timestamp > '2024-07-29' `

**Expected behavior**
I am expecting the query to get the timestamps without any error.

**Versions**

- Version of package with the problem: `version = '0.7.0'`
- ClickHouse server version. `24.1.3.31`
- Python version: `3.9.19`

**Comment by IlluvatarEru** [comment]
Closing - wrong package
