### ISSUE TITLE
Error if enum key is blank

### ISSUE THREAD

**Issue by subuk** [mymarilyn/clickhouse-driver#48]
## How to reproduce

Create table with enum field and insert a few rows
```SQL
DROP TABLE IF EXISTS events;
CREATE TABLE events (
    time DateTime('UTC'),
    project Enum8('' = 0, 'first' = 1),
    text String
) ENGINE = MergeTree() ORDER BY (time) PARTITION BY toYYYYMM(time);

INSERT INTO events VALUES(now(), 'first', 'descr1');
INSERT INTO events VALUES(now(), '', 'descr2');
```

Try to select with python driver:
```python
import clickhouse_driver
client = clickhouse_driver.Client(host='127.0.0.1')
print(client.execute("SELECT * FROM events"))
```

```
Traceback (most recent call last):
  File "/tmp/driver-test.py", line 4, in <module>
    print(client.execute("SELECT * FROM events"))
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 189, in execute
    types_check=types_check, columnar=columnar
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 246, in process_ordinary_query
    columnar=columnar)
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 82, in receive_result
    self.receive_no_progress_result(result, columnar)
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 109, in receive_no_progress_result
    packet = self.receive_packet()
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/client.py", line 140, in receive_packet
    packet = self.connection.receive_packet()
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/connection.py", line 334, in receive_packet
    packet.block = self.receive_data()
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/connection.py", line 393, in receive_data
    block = self.block_in.read()
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/streams/native.py", line 80, in read
    self.fin)
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/columns/service.py", line 67, in read_column
    column = get_column_by_spec(column_spec, column_options=column_options)
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/columns/service.py", line 45, in get_column_by_spec
    return create_enum_column(spec, column_options)
  File "/Users/name/pyenv/lib/python2.7/site-packages/clickhouse_driver/columns/enumcolumn.py", line 67, in create_enum_column
    return cls(Enum(cls.ch_type, d), **column_options)
  File "/Users/name/pyenv/lib/python2.7/site-packages/enum/__init__.py", line 349, in __call__
    return cls._create_(value, names, module=module, type=type, start=start)
  File "/Users/name/pyenv/lib/python2.7/site-packages/enum/__init__.py", line 462, in _create_
    classdict[member_name] = member_value
  File "/Users/name/pyenv/lib/python2.7/site-packages/enum/__init__.py", line 125, in __setitem__
    if _is_sunder(key):
  File "/Users/name/pyenv/lib/python2.7/site-packages/enum/__init__.py", line 80, in _is_sunder
    return (name[0] == name[-1] == '_' and
IndexError: string index out of range
```

**Comment by xzkostyan** [comment]
Hi.

We cannot construct enum with empty value:

```python
In [1]: In [3]: from enum import Enum
   ...: 
   ...: In [4]: Enum('A', {u'': 0, u'first': 1})
   ...: 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-d9310536d192> in <module>()
      1 from enum import Enum
      2 
----> 3 Enum('A', {u'': 0, u'first': 1})

.../local/lib/python2.7/site-packages/enum/__init__.pyc in __call__(cls, value, names, module, type, start)
    347             return cls.__new__(cls, value)
    348         # otherwise, functional API: we're creating a new Enum type
--> 349         return cls._create_(value, names, module=module, type=type, start=start)
    350 
    351     def __contains__(cls, member):

.../local/lib/python2.7/site-packages/enum/__init__.pyc in _create_(cls, class_name, names, module, type, start)
    460             else:
    461                 member_name, member_value = item
--> 462             classdict[member_name] = member_value
    463             _order_.append(member_name)
    464         # only set _order_ in classdict if name/value was not from a mapping

.../local/lib/python2.7/site-packages/enum/__init__.pyc in __setitem__(self, key, value)
    123         elif key == '__order__':
    124             key = '_order_'
--> 125         if _is_sunder(key):
    126             if key != '_order_':
    127                 raise ValueError('_names_ are reserved for future Enum use')

.../local/lib/python2.7/site-packages/enum/__init__.pyc in _is_sunder(name)
     78 def _is_sunder(name):
     79     """Returns True if a _sunder_ name, False otherwise."""
---> 80     return (name[0] == name[-1] == '_' and
     81             name[1:2] != '_' and
     82             name[-2:-1] != '_' and

IndexError: string index out of range
```

**Comment by subuk** [comment]
Yes, python enums cannot, but clickhouse can, so I think that this is the problem and should be fixed.

**Comment by xzkostyan** [comment]
Now CH enum is mapped into python's enum. But python's enum doesn't support blank values.

How driver should handle this case? Use sentinel for blank value?

**Comment by subuk** [comment]
I don't know too, but problem exists. Maybe driver should not use python's enum for validation at all?

**Comment by furmanOFF** [comment]
Cowboy-style fix is patching python's enum module. 
Checked on 2.7.x, but should be OK with 3.x

```python
import enum

def _is_sunder_fix(name):
    """Returns True if a _sunder_ name, False otherwise.
    Patched: doesn't crash on empty strings
    """
    return (name[:1] == name[-1:] == '_' and
            name[1:2] != '_' and
            name[-2:-1] != '_' and
            len(name) > 2)

enum._is_sunder = _is_sunder_fix
```

**Comment by xzkostyan** [comment]
@subuk does this fix cover your case?

**Comment by subuk** [comment]
Yes, monkey patch can solve any case and my too.
I think it is not only my case, but issue in the driver, if you don't think so and do not want to fix anything, just mention such incompatibility in readme and close this issue.

**Comment by xzkostyan** [comment]
There is no guarantee that any other module will not patch `enum` module in other way. So I think it's bad idea to patch standard library if you do not really have to. Okay, I'll organize small page of known issues and the way they can be fixed.

If this issue will happen too often we will think about it again.

**Comment by AbdullaevAPo** [comment]
This problem happened to me too. Can you, please fix it?

**Comment by xzkostyan** [comment]
Hi, this behavior was documented https://clickhouse-driver.readthedocs.io/en/latest/types.html#enum8-16.

**Comment by saulpw** [comment]
This issue happens even with the [database that Clickhouse has set up as a playground](https://clickhouse.com/docs/en/getting-started/playground/) at `clickhouse://explorer@play.clickhouse.com:9440/`.  The `cell_towers` table has a `Radio` Enum column with the 0 value being an empty string.  The enum patch is clever but I agree with @xzkostyan that we shouldn't have to patch the stdlib to fix this.  I suggest something like this patch, which replaces the empty string with an underscore sentinel:

```
diff --git a/clickhouse_driver/columns/enumcolumn.py b/clickhouse_driver/columns/enumcolumn.py
index 60cd808..2372f4c 100644
--- a/clickhouse_driver/columns/enumcolumn.py
+++ b/clickhouse_driver/columns/enumcolumn.py
@@ -73,7 +73,8 @@ def create_enum_column(spec, column_options):
         params = spec[7:-1]
         cls = Enum16Column
 
-    return cls(Enum(cls.ch_type, _parse_options(params)), **column_options)
+    values = {(k or '_'): v for k, v in _parse_options(params).items()}
+    return cls(Enum(cls.ch_type, values), **column_options)
```
