### ISSUE TITLE
Error writing string while using supserset and clickhouse driver (text encode not set to UTF-8)

### ISSUE THREAD

**Issue by Matt-Texier** [mymarilyn/clickhouse-driver#56]
Hi,

Something new is happening while adding a clickhouse db to supserset at the time superset is trying to get table meta data.

```
Traceback (most recent call last):
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/superset/views/core.py", line 1764, in testconn
    return json_success(json.dumps(engine.table_names(), indent=4))
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2139, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "<string>", line 2, in get_table_names
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/reflection.py", line 42, in cache
    return fn(self, con, *args, **kw)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 482, in get_table_names
    return [row.name for row in self._execute(connection, 'SHOW TABLES')]
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_sqlalchemy/drivers/native/base.py", line 34, in _execute
    return connection.execute(sql)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 492, in do_execute
    cursor.execute(statement, parameters, context=context)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_sqlalchemy/drivers/native/connector.py", line 125, in execute
    external_tables=external_tables, settings=settings
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_driver/client.py", line 102, in execute
    self.connection.force_connect()
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_driver/connection.py", line 124, in force_connect
    self.connect()
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_driver/connection.py", line 189, in connect
    self.send_hello()
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_driver/connection.py", line 260, in send_hello
    write_binary_str(self.password, self.fout)
  File "/home/matthieu/python-venv/super-modular/lib/python3.5/site-packages/clickhouse_driver/writer.py", line 18, in write_binary_str
    text = text.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
2018-09-25 21:09:57,639:INFO:werkzeug:127.0.0.1 - - [25/Sep/2018 21:09:57] "POST /superset/testconn HTTP/1.1" 500 -
```

I suspect that something has changed in a new version of the driver and that now it is checking that there is no none UTF-8 bytes in the string before storing it ?

How do you suggest me to fix that ? Is it something to be set on string sent by superset or is it something on clickhouse driver ?

Thanks Matthieu.

**Comment by Matt-Texier** [comment]
I had a doubt in my development machine and my various venv but even after fixing it, I still have the same problem ... Maybe a newbie question ... but I was not able to find the problem.

Thanks Matthieu.

**Comment by Matt-Texier** [comment]
It is me being an idiot, problem solved ... sorry.

**Comment by Dionid** [comment]
@Matt-Texier So how do you solved it?

**Comment by krutik228** [comment]
For such people a separate frying pan in hell ...
