### ISSUE TITLE
Big INSERT ends in timeout

### ISSUE THREAD

**Issue by knutknudsen** [mymarilyn/clickhouse-driver#8]
Hi, 

I have an issue with a big insert query > 2000 cols. 
Finally it runs with native clickhouse client.
After some config changes runs in 0.5 seconds

Now I tried to run the same query with the clickhouse-driver.
It times out.

Before I had the same script working with pymysql.

Any idea how to fix this?

Traceback (most recent call last):
  File "Click_v01.py", line 154, in <module>
    client.execute(sql)
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/client.py", line 73, in execute
    query_id=query_id, settings=settings
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/client.py", line 88, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types)
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/client.py", line 19, in receive_result
    block = self.receive_block()
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/client.py", line 38, in receive_block
    packet = self.connection.receive_packet()
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/connection.py", line 234, in receive_packet
    packet.type = packet_type = read_varint(self.fin)
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/reader.py", line 46, in read_varint
    i = _read_one(f)
  File "/usr/lib/python3.4/site-packages/clickhouse_driver/reader.py", line 31, in _read_one
    c = f.read(1)
  File "/usr/lib64/python3.4/socket.py", line 378, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by xzkostyan** [comment]
Hi!

How do you emit insert query? It seems that you are trying to do something like:
```python
client.execute("INSERT INTO test (x) VALUES (1), (2)")
```

But the client doesn't parse query like `clickhouse-client`. The proper way of emitting INSERT query:
```python
client.execute(
    'INSERT INTO test (x) VALUES',
    [{'x': 1}, {'x': 2}, {'x': 3}, {'x': 100}]
)
client.execute('INSERT INTO test (x) VALUES', [[200]])
```

See examples of usage: https://github.com/mymarilyn/clickhouse-driver.

**Comment by knutknudsen** [comment]
You're right, that fixed it.
Thanks
